### ISSUE TITLE
Expose a API on localhost?

### ISSUE THREAD

**Issue by webdevbrian** [kris701/ArduLED#4]
Kris -- great work on this. I cannot wait to get started using this! I have 4 shelved projects that were literally relying on this type of application.

Two of the projects that I have are nodeJS applications that run on a mac mini that I have in a bar that I have in my garage. It runs a few services, one being a service via IoT that when I flip on one of my neon signs around my bar, it runs a text messaging service and pings all of my mates that the bar is open and to run over to my place, among some silly / fun other things. The main purpose, is that it functions as the brain for this space specifically, which really got me thinking.

Off the top of my head - what would be amazing is an exposed API through ArduLED that my node apps could utilize to control the LEDs. I have a few 5M strips that I have three teensys running different patterns all independently (one's in a porthole above my urinal, the other in the couch area, and the final is a wall-art grid that was going to be a coffee table, but I ended up taking the legs off of it).

Being able to push / control patterns based on webAPI requests (sockets, specifically) would send these projects into another dimension. For example, getting scoring data from webAPIs in my nodeJS apps and being able to control patterns / set strip colors, etc.

Because users will be using this on a computer, this really opens up pandoras box with what people could use it for (and I'm excited to even start thinking about). Live twitch stream feed back / effects (subscriptions, donations etc), visual feedback for input devices (keyboards, mice, joysticks, wheels, pedals) visual feedback for voice servers like TeamSpeak / Ventrillo, Chatroom feedback for live streamers, visual feedback for system related information (CPU load, temperature, etc) ... lots and lots of great ideas that could be easily achieved. Exposing the IP through a firewall could even be used for IoT feedback (doors left open, not closed, sensors triggered etc).

I wouldn't mind helping at all with this any way I can if you think this is a good idea.

**Comment by kris701** [comment]
That is not a bad idear, however i am not that well known with C# and web stuff. But i have played arround with ASP.NET before, and i guess it is something like that i would need to implement right? Something like this: https://hashben.wordpress.com/2013/03/24/control-arduino-from-asp-net-c-web-application-interface/
But i dont know, please do tell me if this is what you are thinking.

**Comment by webdevbrian** [comment]
Along those lines, yes!

Essentially you will need to expose controlling the strips the way you have done in C#, through an REST API request. Things like POST / GET could be used. POSTing for updating a strip, GETing for getting the current status of a strip. You could use PUT and DELETE to interface with the application you developed, maybe even exposing creating patterns the way you have currently with your "Instructions" mode (the save / deleting). Just some quick ideas.

The response codes could further provide information on the application -> strip connectivity as well.

This may be a starting point: https://docs.microsoft.com/en-us/aspnet/web-api/overview/older-versions/build-restful-apis-with-aspnet-web-api

Could be fun to look at when you get a chance!

**Comment by kris701** [comment]
First implementation of the local API is done, also includes a test tool, to write directly to ArduLED through the API. Updating the wiki now, so you can see the API specification :)

**Comment by kris701** [comment]
There we go, all the commands are now under the wiki (https://github.com/kris701/ArduLED/wiki/Server-API) please do tell if there is something more i need to add, or if something is not working. And thanks for the suggestion ^^

**Comment by webdevbrian** [comment]
I will start testing this tonight! I'll add to the wiki if I can and will start writing some unit tests locally. 

Fantastic work @kris701 !

**Comment by kris701** [comment]
That would be wonderfull (since i just wrote some of the basics on the wiki)
