### ISSUE TITLE
Trouble compiling the .ino file

### ISSUE THREAD

**Issue by PedroHIPs** [kris701/ArduLED#8]
I'm having some trouble uploading the ArduLED_Arduino.ino file.

I try to upload the file but i'm getting this errors:
C:\Users\Pedro HIPs\Desktop\ArduLED-master\Stable version\ArduLED\ArduLED_Arduino\ArduLED_Arduino.ino: In function 'void setup()':
C:\Users\Pedro HIPs\Desktop\ArduLED-master\Stable version\ArduLED\ArduLED_Arduino\ArduLED_Arduino.ino:21:60: warning: narrowing conversion of '256' from 'int' to 'uint8_t {aka unsigned char}' inside { } [-Wnarrowing]
  const uint8_t PixelBitrates[2] = { NEO_KHZ800, NEO_KHZ400 };
                                                            ^
C:\Users\Pedro HIPs\Desktop\ArduLED-master\Stable version\ArduLED\ArduLED_Arduino\ArduLED_Arduino.ino:21:60: warning: large integer implicitly truncated to unsigned type [-Woverflow]
C:\Users\PEDROH~1\AppData\Local\Temp\ccH3IdIi.ltrans0.ltrans.o: In function `ColorEntireStripFromTo':
C:\Users\Pedro HIPs\Desktop\ArduLED-master\Stable version\ArduLED\ArduLED_Arduino/ArduLED_Arduino.ino:818:(.text+0xb44): relocation truncated to fit: R_AVR_7_PCREL against `no symbol'
collect2.exe: error: ld returned 1 exit status
exit status 1
Erro compilando para a placa Arduino Nano

I Know that is a Closed Project, but i will be so thankful if you help-me.

**Comment by kris701** [comment]
I belive that the library that i used in this have been changed a bit, so i sadly dont think that it works no more.
I dont work on this anymore, and i sadly do not have the time to fix this.

Sorry for your trouble ^^

**Comment by PedroHIPs** [comment]
No worries. Just asking, you doesn't work on ArduLED 1.0 only, or you doesn't work on ArduLED at all?

**Comment by kris701** [comment]
Yeah i dont work on any ArduLED project no more, sadly i do not have the time
